# Generated by Django 4.2.1 on 2023-05-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_description_user_title_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
