# Generated by Django 4.2.1 on 2023-05-07 00:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('button1', models.IntegerField(default=0)),
                ('button2', models.IntegerField(default=0)),
                ('loggedAt', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 19, 46, 32, 49922))),
                ('loggedOut', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
