# Generated by Django 4.2.1 on 2023-05-07 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0005_alter_session_loggedat_alter_session_loggedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='loggedAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 16, 8, 53, 836956)),
        ),
    ]
